import Head from "next/head";
import { type NextPage } from "next";
import Link from "next/link";
import { UserButton, useUser} from "@clerk/nextjs";
import {LoadingSpinner, LoadingPage} from "~/components/loading"
import { toast } from "react-hot-toast";
import { RouterOutputs, api } from "~/utils/api";


const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className = "flex justify-center h-full">
        <div>
            Post View
        </div>
      </main>
    </>
  );
}
export default SinglePostPage;
